# Generated by Django 5.0.1 on 2024-06-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='umai',
            new_name='uemail',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
