# Generated by Django 5.0.1 on 2024-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0002_rename_umai_user_uemail_alter_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
