# Generated by Django 5.0.1 on 2024-06-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
