# Generated by Django 5.0.1 on 2024-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0006_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestData',
            fields=[
                ('uid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
