# Generated by Django 5.0.1 on 2024-06-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0008_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
