# Generated by Django 5.0.1 on 2024-06-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0010_rename_status_requestdata_examd_requestdata_hod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdata',
            name='secD',
            field=models.BooleanField(default=False),
        ),
    ]
