# Generated by Django 5.0.1 on 2024-06-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0011_requestdata_secd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
